### ISSUE TITLE
Ronin Server is missing Settings Gear

### ISSUE THREAD

**Issue by gnagleCFS** [coolfiresolutions/ronin-service-desk#1]
**Describe the bug**
There is no settings gear to allow access to user management like the Cloud server has. Can /admin or /audit and see screens if one knows that trick. 

**Where are you seeing this?**
Ronin Server running standalone on installed on laptop or PacStar server hardware

**To Reproduce**
Load Ronin server on a laptop following directions in the manual if possible, or get Dev to help install it
Log in from chrome browser as admin. 
Look for gear in lower left. 
Notice its not there. 

**Expected behavior**
Expected to see gear similar to cloud based server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 running VMWare
 

**Smartphone (please complete the following information):**
 - Device: Del laptop
 - OS: win10
 - Browser Chrome
 - Version unknown

**Additional context**
none

**Comment by cfsbhawkins** [comment]
Fixed issue, Seed data was wrong on the admin user role.
