### ISSUE TITLE
Inactive Markers

### ISSUE THREAD

**Issue by gnagleCFS** [coolfiresolutions/ronin-service-desk#11]
**Is your improvement or feature request related to a problem? Please describe.**
Markers appear on both Web UI & Android App even if not active. App will not update or clear Markers when 'off-air' 
IMPACT: Confusing and dangerous for user

**Where would you like to see this improvement or feature request?**
Both Ronin Server Browser and SA Patrol Android

**Describe the solution you'd like**
Ability to Clear Markers. 

**Describe alternatives you've considered**

**Additional context**
 Screenshot is shown in RT007/RT007-1 shown in this directory:
https://drive.google.com/drive/folders/1mcQV2JBOOQOTnZ-5XO5mdzp_GiLOLQc_

**Comment by cfsbhawkins** [comment]
Link in invalid, please upload any attachments to the ticket.

**Comment by gnagleCFS** [comment]
Uploaded image because link doesn't work
![RT007-Old Markers](https://user-images.githubusercontent.com/80912036/112902859-c5160600-90b4-11eb-9d35-e0c015b39dc9.jpg)
![RT007-1-Old Markers](https://user-images.githubusercontent.com/80912036/112902908-d65f1280-90b4-11eb-8652-e92d4f02cf57.jpg)

**Comment by cfsbhawkins** [comment]
dup: #4 linking and closing.
