### ISSUE TITLE
Ronin Geofencing - WebUI

### ISSUE THREAD

**Issue by awshep** [coolfiresolutions/ronin-service-desk#13]
**Describe the bug**
Geofences cannot be moved or changed once created in Web UI. User has to delete current Geofence and then create another one

**Where are you seeing this?**
WebUI Server

**To Reproduce**
User has to delete current Geofence and then create another one

**Expected behavior**
User needs to select an existing geofence and be able to move or change it real-time on the map.

**Screenshots**
See screenshot RT010

**Desktop (please complete the following information):**
 - Chrome - Ronin Server

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
Current operation and maintenance of geofences is cumbersome for user
![RT010-Geofencing](https://user-images.githubusercontent.com/81593928/112905414-5cc92380-90b8-11eb-8cc7-26c9b8753087.jpg)

**Comment by cfsadellamano** [comment]
You can edit an existing geofence on the web app. Click on the geofence and you will see an "edit" button near the map's zoom tools. This will allow you to modify the shape of the geofence and it's attributes.

<img width="1079" alt="Screen Shot 2021-03-30 at 3 16 15 PM" src="https://user-images.githubusercontent.com/14224373/113050963-1254af00-916b-11eb-8611-67424576ad26.png">
