### ISSUE TITLE
Ronin server install and map loading instructions are missing from the current manual (3/1/2021) 

### ISSUE THREAD

**Issue by gnagleCFS** [coolfiresolutions/ronin-service-desk#2]
**Describe the bug**
It is very difficult to install Ronin server and load the necessary maps using the instructions in the current version of the manual. Suggest step by step instructions be added and then validated.

**Where are you seeing this?**
When trying to install and set up Ronin

**To Reproduce**
Attempt to install Ronin on a laptop viewed from the perspective of a first time customer, using the manual. 
After installation, attempt to create maps and load them on the server for the desired area of operation, using the instructions in the manual.  

**Expected behavior**
Should be able to install and load maps in the desired area of operation

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cfsbhawkins** [comment]
I believe this has been taken care of over the weekend by Dan.

**Comment by gnagleCFS** [comment]
Hector,
Below says the manual is complete. If so, has it been verified, and where can I get a copy?
Gary

Sent from my iPhone

> On Mar 23, 2021, at 5:16 PM, Brian Hawkins ***@***.***> wrote:
> 
> ﻿
> I believe this has been taken care of over the weekend by Dan.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
_*STATEMENT OF CONFIDENTIALITY:* This Email is covered by the Electronic 
Communications Privacy Act, 18 U.S.C. §§2510-2521 and is legally 
privileged. The information contained in this electronic message and any 
attachments thereto are intended for the exclusive use of the addressees 
and may contain confidential and/or privileged information. If you are not 
the intended recipient, please inform the sender immediately via telephone, 
fax or reply e-mail and delete all copies of this message and all 
attachments from your system._

**Comment by cfsbhawkins** [comment]
I have reviewed the updated documentation and I am satisfied that the instructions have been added, and additional details given around editing the maptile settings.
