### ISSUE TITLE
Ronin Android - Group Messaging Imagery

### ISSUE THREAD

**Issue by awshep** [coolfiresolutions/ronin-service-desk#20]
**Describe the bug**
Trying to send an attached picture to group message, but it won't send. 
Test 1: Standalone Server with Radio Test setup with Getac MX50. Never sent, an get a continuous spin icon.
Test 2: Ronin Mil Web Server sending from Getac. Sent apparently, but could not pull up sent pic from the sending unit. Received by one user, and inconsistent received by the other.
Test 3: Ronin Mil Web Server sending from Pixel, logged on w same user as previous test. This time the previously sent message can be seen, that could not be seen from Getac. Sent another pic, and that one appears to work as it should

**Where are you seeing this?**
Android

**To Reproduce**
See above

**Expected behavior**
User wants to take pic and attach to share/update SITREP, as shown in menu, but looses pic  on his device. 

**Screenshots**

**Desktop (please complete the following information):**
 - Android

**Smartphone (please complete the following information):**
 - Getac MX50

**Additional context**

**Comment by cfsbhawkins** [comment]
dup: #3 closing
