### ISSUE TITLE
Ronin WebUI Settings Gear

### ISSUE THREAD

**Issue by awshep** [coolfiresolutions/ronin-service-desk#21]
**Describe the bug**
There is no settings gear to allow access to user management like the Cloud server has. Can /admin or /audit and see screens if one knows that trick.

**Where are you seeing this?**
On home Screen

**To Reproduce**
As above

**Expected behavior**
Need Settings gear

**Screenshots**

**Desktop (please complete the following information):**
Win UI

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cfsbhawkins** [comment]
Duplicate, already resolved.
